### ISSUE TITLE
patreon version no work

### ISSUE THREAD

**Issue by jeweleryoflight** [Coloured568/Day-Walkers#1]
![image](https://github.com/user-attachments/assets/14c817bc-0c32-4b35-ae04-2977bec65b09)
![image](https://github.com/user-attachments/assets/c04e8ef2-be4c-4b7d-86c7-0dfdc39601cc)

**Comment by iLollek** [comment]
Huh, this is interesting. I'm making a Mod myself right now (Music Changer Mod) and I thought the Assemblies are mostly the same.

But I guess by just changing the Assembly inside MelonLoader this could be easily fixed..

**Comment by Coloured568** [comment]
fixed in update v2.0.0
